version: '3.7'

services:
  node:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    container_name: digemy-tech-assessment-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    networks:
      - digemy-tech-assessment
    command: sh -c "npm ci && npm run build"
    environment:
      - NODE_ENV=production

